services:

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: smartcare-mosquitto
    ports:
      - "1883:1883"  # MQTT in chiaro (solo debug locale)
      - "8883:8883"  # MQTT sicuro con TLS (App / Backend)
      - "9002:9002"  # WebSocket sicuro con TLS (Dashboard Browser)
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/certs:/mosquitto/certs:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log          
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: smartcare-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: smartcare2026
      MONGO_INITDB_DATABASE: smartcare
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: smartcare-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: smartcare2026
      MYSQL_DATABASE: smartcare
      MYSQL_USER: smartcare
      MYSQL_PASSWORD: smartcare2026
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mongo_data:
  mysql_data: